packages:
  - "packages/*"
  - "apps/*"
  - "../rafters/packages/ui"

catalog:
  "@axe-core/playwright": ^4.11.0
  "@testing-library/jest-dom": ^6.6.3
  "@testing-library/react": ^16.1.0
  "@testing-library/user-event": ^14.5.2
  "@types/react": ^19.0.0
  "@types/react-dom": ^19.0.0
  "@vitejs/plugin-react": ^4.3.4
  "@vitest/coverage-v8": ^3.2.0
  happy-dom: ^20.0.10
  react: ^19.2.0
  react-dom: ^19.2.0
  typescript: 5.9.3
  vitest: ^3.2.0
  vitest-axe: ^1.0.0-pre.3
  zod: ^4.0.0
